### ISSUE TITLE
無法自動啓動autostart.sh腳本

### ISSUE THREAD

**Issue by xiaokai1919810** [yaocccc/dwm#15]
每次開機都需要手動啓動
已經將“export DWM=~/workspace/dwm”寫入.profile 但是無濟於事

**Comment by yaocccc** [comment]
1 确认文件是否正确存在 是否在$DWM/autostart.sh

2 判断文件所有人是否是user而非root
3 判断是否有可执行权限

**Comment by xiaokai1919810** [comment]
條件都滿足 但是不行

**Comment by xiaokai1919810** [comment]
我把config.h中的static const char *autostartscript = "$DWM/autostart.sh";更改爲了static const char *autostartscript = "~/workspace/dwm/autostart.sh";就可以了
問題解決

**Comment by xiaokai1919810** [comment]
謝謝！

**Comment by yaocccc** [comment]
> 我把config.h中的static const char *autostartscript = "$DWM/autostart.sh";更改爲了static const char *autostartscript = "~/workspace/dwm/autostart.sh";就可以了 問題解決

okk, 看来是启动dwm的时候，DWM环境变量还没设置
