### ISSUE TITLE
非正常退出dwm导致状态栏失效

### ISSUE THREAD

**Issue by gaogao-qwq** [yaocccc/dwm#17]
非正常退出 dwm 如断电、强制关机，statusbar.sh 会残留一份 temp 文件，使得下一次开机后 statusbar.sh 无法正常工作。可以通过删除 temp 文件恢复正常，也许可以在脚本中加个特判预防这种情况？

**Comment by yaocccc** [comment]
比较简单的方法，在cron里加一行echo它的指令，置空它。我关注一下
