### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by ibepo** [yaocccc/dwm#2]
可以列出打了哪些 patch 吗

**Comment by yaocccc** [comment]
答不出来哈，主要是改了代码居多，打补丁已经是最早最早的时候的事情了。

你可以去看一下 theniceboy(thecw)的仓库，我最早是copy的他的基础上改的

https://github.com/theniceboy/dwm
[https://opengraph.githubassets.com/86e478036af0b35bf72630b3aaa29f4e3ba37ced10b139eba82b2dc3cdd57227/theniceboy/dwm]<https://github.com/theniceboy/dwm>
theniceboy/dwm: A bloated build of dwm with systemtray, gaps, customized tags and other appearance changes - GitHub<https://github.com/theniceboy/dwm>
David's build of dwm. 中文版. dwm is an extremely fast, small, and dynamic window manager for X. BTW, my scripts are in this repo.. Requirements. In order to build dwm you need the Xlib header files.
github.com

________________________________
发件人: ibepo ***@***.***>
发送时间: 2022年7月29日 1:03
收件人: yaocccc/dwm ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yaocccc/dwm] patch (Issue #2)


可以列出打了哪些 patch 吗

―

**Comment by ibepo** [comment]
其实我是想把task那里的宽度等分，试了试没成功

**Comment by yaocccc** [comment]
看一下drawbar这个func，当时我是改了这里面的内容来让自己有空余的空间

**Comment by fecet** [comment]
我用的也是在theCW的基础上改的，一直想换但是不想舍弃scratchpad功能(就是在屏幕中间开一个终端，各个window间共享），这个patch和这个repo兼容吗

**Comment by yaocccc** [comment]
> 我用的也是在theCW的基础上改的，一直想换但是不想舍弃scratchpad功能(就是在屏幕中间开一个终端，各个window间共享），这个patch和这个repo兼容吗

这个原先有，被我删掉了，我的用法是 super -，开一个浮动终端，简单说就是 一个scratchpad 不够我用。我可以给client加一个属性，符合的就全局显示。好像也不错

**Comment by yaocccc** [comment]
> 我用的也是在theCW的基础上改的，一直想换但是不想舍弃scratchpad功能(就是在屏幕中间开一个终端，各个window间共享），这个patch和这个repo兼容吗

https://github.com/yaocccc/dwm/commit/7bcdfb2a584fc2a53d45b37d028f7b19667fafbc

**Comment by fecet** [comment]
试用了一下, 非常方便, 不过我还有个小问题, 怎么能实现像scratchpad一样再按一次就自动隐藏, 第三次按恢复的效果呢

**Comment by yaocccc** [comment]
> 

我这个没有设计类似的逻辑呢，scratchpad是有且只有一个窗口，然后可以做这样的逻辑，我这边的变更是不限定数量的，所以比较不好设计交互。

或许你可以使用 super h，来隐藏这个窗口，super shift h，再使这个窗口重新显示。当然想重新实现scratchpad也行。。。不过我动力不强

**Comment by fecet** [comment]
> > 
> 
> 我这个没有设计类似的逻辑呢，scratchpad是有且只有一个窗口，然后可以做这样的逻辑，我这边的变更是不限定数量的，所以比较不好设计交互。
> 
> 或许你可以使用 super h，来隐藏这个窗口，super shift h，再使这个窗口重新显示。当然想重新实现scratchpad也行。。。不过我动力不强

我有个想法是这个可以设计在应用层面上, 让这个应用支持开关式的操作, 比如 https://github.com/phuhl/linux_notification_center 这个项目就支持
> Toggle between hidden and shown state of the notification center:
>```
>kill -s USR1 $(pidof deadd-notification-center)
>```
st能不能实现类似的功能呢

**Comment by yaocccc** [comment]
> > > 
> > 
> > 
> > 我这个没有设计类似的逻辑呢，scratchpad是有且只有一个窗口，然后可以做这样的逻辑，我这边的变更是不限定数量的，所以比较不好设计交互。
> > 或许你可以使用 super h，来隐藏这个窗口，super shift h，再使这个窗口重新显示。当然想重新实现scratchpad也行。。。不过我动力不强
> 
> 我有个想法是这个可以设计在应用层面上, 让这个应用支持开关式的操作, 比如 https://github.com/phuhl/linux_notification_center 这个项目就支持
> 
> > Toggle between hidden and shown state of the notification center:
> > ```
> > kill -s USR1 $(pidof deadd-notification-center)
> > ```
> 
> st能不能实现类似的功能呢

我在浏览我的下游时发现了这个commit，也许你可以采用类似的方案解决 

https://github.com/Meow-2/dwm/commit/8af7358f59e2a19ce2f8fc65f95f4c049fcbbf9c

**Comment by yaocccc** [comment]
> > > > 
> > > 
> > > 
> > > 我这个没有设计类似的逻辑呢，scratchpad是有且只有一个窗口，然后可以做这样的逻辑，我这边的变更是不限定数量的，所以比较不好设计交互。
> > > 或许你可以使用 super h，来隐藏这个窗口，super shift h，再使这个窗口重新显示。当然想重新实现scratchpad也行。。。不过我动力不强
> > 
> > 
> > 我有个想法是这个可以设计在应用层面上, 让这个应用支持开关式的操作, 比如 https://github.com/phuhl/linux_notification_center 这个项目就支持
> > > Toggle between hidden and shown state of the notification center:
> > > ```
> > > kill -s USR1 $(pidof deadd-notification-center)
> > > ```
> > 
> > 
> > st能不能实现类似的功能呢
> 
> 我在浏览我的下游时发现了这个commit，也许你可以采用类似的方案解决
> 
> [Meow-2@8af7358](https://github.com/Meow-2/dwm/commit/8af7358f59e2a19ce2f8fc65f95f4c049fcbbf9c)

原始的scratchpad实质上干的也是类似的事情，手动指定了一个cmd，然后指定了instance name，匹配已存在则会去hide，不存在则会去创建

**Comment by fecet** [comment]
```
#!/bin/bash

float() {
    alacritty -o "window.dimensions.lines=30" \
        --class global \
        --hold \
        -t "tmux-floatterm" \
        -e zsh -c "tmux -u attach -t float || tmux -u new -s float"
}

kill $(xprop -name "tmux-floatterm" _NET_WM_PID) || float
```
写了个这个, 勉强能用吧

**Comment by yaocccc** [comment]
> ```
> #!/bin/bash
> 
> float() {
>     alacritty -o "window.dimensions.lines=30" \
>         --class global \
>         --hold \
>         -t "tmux-floatterm" \
>         -e zsh -c "tmux -u attach -t float || tmux -u new -s float"
> }
> 
> kill $(xprop -name "tmux-floatterm" _NET_WM_PID) || float
> ```
> 
> 写了个这个, 勉强能用吧

老哥你这也太惨烈了。。。我来吧。

**Comment by yaocccc** [comment]
> ```
> #!/bin/bash
> 
> float() {
>     alacritty -o "window.dimensions.lines=30" \
>         --class global \
>         --hold \
>         -t "tmux-floatterm" \
>         -e zsh -c "tmux -u attach -t float || tmux -u new -s float"
> }
> 
> kill $(xprop -name "tmux-floatterm" _NET_WM_PID) || float
> ```
> 
> 写了个这个, 勉强能用吧

看看这个。。。效果一定比你那个强

https://github.com/yaocccc/dwm/commit/7e0c359f6ddc86f926ded76caa47ad64ed7d6ae6

**Comment by fecet** [comment]
感谢老哥, 我这个效果肯定不如原生的, 回头试一下
