### ISSUE TITLE
修复cpu.sh使用top获取cpu占用率异常

### ISSUE THREAD

**Issue by Cyberczy** [yaocccc/dwm#30]
将
top -n 1 -b | sed -n '3p' | awk '{printf "%02d%", 100 - $8}'
更换为
mpstat 1 1 | awk '$12 ~ /[0-9.]+/ {print 100 - $12"%"}' | sort -u
效果图如下
https://pic.imgdb.cn/item/64bbeab81ddac507ccbb21d4.jpg
第一次提pr抱歉我还不是很会用这个（大概是这么用吧）

**Comment by yaocccc** [comment]
这个问题是，默认无安装

**Comment by Cyberczy** [comment]
这个月上旬我还好好的，前几天好像就突然这样了·

**Comment by yaocccc** [comment]
这个应该是你另外装的东西带了这个命令

**Comment by Cyberczy** [comment]
好的谢谢啦

**Comment by yaocccc** [comment]
嗯嗯，top就是足够简单。我其实都不看占用，，主要看温度

**Comment by Cyberczy** [comment]
hh温度那一块没问题的

**Comment by solitudealma** [comment]
笑死 我一个都执行不了 在nixos上 问了半天ai问出了这个
```shell
mpstat -P ALL 1 1 | grep "Average:" | head -n 2 | tail -n 1 | awk '{print 100 - $12}'
sensors | grep 'Package id 0' | awk '{print $4}' | sed 's/[^0-9.]*//g'
```
听ai说的是系统不一样这些东西都不一样 特别是温度这里
