### ISSUE TITLE
状态栏关闭的情况下应用全屏需要先开启状态栏

### ISSUE THREAD

**Issue by BingCoke** [yaocccc/dwm#34]
这是特性还是bug。。。
![image](https://github.com/yaocccc/dwm/assets/81607010/a7a61c8f-1b7e-4baa-a20d-95821aaccfc7)

按下全屏
![image](https://github.com/yaocccc/dwm/assets/81607010/85856b47-9818-4483-aaa3-f0e893ef684e)
会先开启状态栏

**Comment by yaocccc** [comment]
是特性

**Comment by yaocccc** [comment]
![image](https://github.com/yaocccc/dwm/assets/53512609/9d487633-243b-4a99-a8aa-319e077ba279)

**Comment by BingCoke** [comment]
> ![image](https://user-images.githubusercontent.com/53512609/265007013-9d487633-243b-4a99-a8aa-319e077ba279.png)

Ok 改了一下可以了 谢谢啦

**Comment by BingCoke** [comment]
ok 改了一下可以了 谢谢啦
