### ISSUE TITLE
大佬有没有兴趣支持一下gnome提出的马赛克模式

### ISSUE THREAD

**Issue by Asthestarsfalll** [yaocccc/dwm#35]
具体见[此](https://blogs.gnome.org/tbernard/2023/07/26/rethinking-window-management/)，类似于调整窗口大小时不会变为float模式，而是同步地调整整体布局，使其不相互遮挡，以及一些其他特性，不过我认为最重要的就是这个。

**Comment by yaocccc** [comment]
有点难搞的，dwm还是太原始了，如果搞很多这种图形相关的，会非常难搞
