### ISSUE TITLE
音量一直都显示--%,实在是找不到问题le

### ISSUE THREAD

**Issue by lixiaya** [yaocccc/dwm#37]
![image](https://github.com/yaocccc/dwm/assets/128228011/6df8e4b7-6825-43b6-a19e-f847f308714f)
pactl info
服务器字串：/run/user/1000/pulse/native
程序库协议版本：35
服务器协议版本：35
是否本地服务器：是
客户端索引：103
区块大小: 65472
用户名：lxzero
主机名：archlinuxCN
服务器名：pulseaudio
服务器版本：16.1
默认采样规格：s16le 2ch 44100Hz
默认声道映射：front-left,front-right
默认音频入口：alsa_output.pci-0000_00_1f.3.analog-stereo
默认信源： alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie：80f4:5aef

**Comment by lixiaya** [comment]
搞好了，之前静音忘了关了QAQ

**Comment by yaocccc** [comment]
没错了，遇事不决就看脚本
