### ISSUE TITLE
终端透明效果没出来

### ISSUE THREAD

**Issue by hhcwyx** [yaocccc/dwm#38]
操作系统：manjaro
st，kitty，alacritty终端都没有透明效果。
终端配置文件里都设置了相应的透明参数。

**Comment by yaocccc** [comment]
https://yaocc.cc/linuxpicomanimation/

**Comment by hhcwyx** [comment]
谢谢！

是这条命令picom --experimental-backends --config ~/scripts/config/picom.conf没起作用。改为：
picom  --config ~/scripts/config/picom.conf这样就行了。
