### ISSUE TITLE
透明设置可以设置成浏览器不透明吗？

### ISSUE THREAD

**Issue by hhcwyx** [yaocccc/dwm#40]
浏览网页的时候，桌面图案会透上来，感觉不是很舒服，请问能单独设置成浏览器不透明吗？

**Comment by yaocccc** [comment]
> 浏览网页的时候，桌面图案会透上来，感觉不是很舒服，请问能单独设置成浏览器不透明吗？

https://yaocc.cc/linuxpicomanimation/

你的重点还是要去研究下picom的配置怎么写
