### ISSUE TITLE
yay安装字体失败

### ISSUE THREAD

**Issue by antnesswcm** [yaocccc/dwm#48]
这是我使用yay安装nerd-fonts-jetbrains-mono时出现的问题，似乎我的软件源中找不到该字体，这是我初次使用yay，请帮助我，谢谢
```
$ yay -S nerd-fonts-jetbrains-mono
 -> No AUR package found for nerd-fonts-jetbrains-mono
 there is nothing to do
```
-----
正在尝试手动安装nerd修补后的jetbrains-mono.....

**Comment by antnesswcm** [comment]
arch 源中存在 [ttf-jetbrains-mono-nerd](https://archlinux.org/packages/extra/any/ttf-jetbrains-mono-nerd/) 我已经安装了他

所以"nerd-fonts-jetbrains-mono" 是笔误吗?

**Comment by EssenSea** [comment]
字体显示不全， 通过yay 安装readme 提示字体，yay 报错信息如下： jetbrains 不存在，  material icons 不存在

 -> No AUR package found for nerd-fonts-jetbrains-mono
AUR Explicit (1): ttf-all-the-icons-5.0.0-1
Sync Explicit (2): ttf-joypixels-8.0.0-2, wqy-microhei-0.2.0_beta-12
:: (1/1) Downloaded PKGBUILD: ttf-all-the-icons
  1 ttf-all-the-icons                (Build Files Exist)

通过paru 安装 ttf-material-design-icons-git ,  ttf-jetbrains-mono-nerd 然而 似乎并不能解决字体显示不全

**Comment by antnesswcm** [comment]
> 字体显示不全， 通过yay 安装readme 提示字体，yay 报错信息如下： jetbrains 不存在， material icons 不存在
> 
> -> No AUR package found for nerd-fonts-jetbrains-mono AUR Explicit (1): ttf-all-the-icons-5.0.0-1 Sync Explicit (2): ttf-joypixels-8.0.0-2, wqy-microhei-0.2.0_beta-12 :: (1/1) Downloaded PKGBUILD: ttf-all-the-icons 1 ttf-all-the-icons (Build Files Exist)
> 
> 通过paru 安装 ttf-material-design-icons-git , ttf-jetbrains-mono-nerd 然而 似乎并不能解决字体显示不全

你好，我研究过，由于这些字体符号是在作者的脚本中定义的，这些icon font属于nerd扩展字体集

由于nerd字体集的变动导致某些字体的编码位置发生了变化，在新版本的nerd字体中，旧的icon符号将无法显示导致乱码

解决方案是使用 [nerd字符搜索](https://www.nerdfonts.com/cheat-sheet) 旧的字体，得到坏的编码，然后查找新的编码，然后将字符复制到所使用的脚本中


例如，修复wifi图标，这个图标在这个脚本中定义:
![image](https://github.com/user-attachments/assets/33bcc240-b9a5-4878-97b0-877b4f03085d)

复制这个乱码icon，"褐"(这里这个乱码刚好显示为中文，比较好找，但是往往显示为空白，需要仔细找出icon字符)

然后粘贴到nerd搜索中查找:
![image](https://github.com/user-attachments/assets/17057910-f2cc-4462-abec-95eec3a435a8)
得到英文描述后，搜索描述:
![image](https://github.com/user-attachments/assets/252b65a0-dc4c-494a-9a2f-ffa47d83c95d)

然后选出你要替换的字符，点击copy中的icon，将它与乱码替换，显示就可以正常了(前提是你的编辑器显示使用的字体是nerd修补过的，并且版本比较新)

对于脚本，保存后重启dwm即可，对于dwm的config.h等文件中的icon，需要在修改后执行 `sudo make clean install` 重新安装

===

上述的例子中，新搜索的图标中没有与remove图标一样的，是少数，一般是这样:

![image](https://github.com/user-attachments/assets/b929e82d-4613-4ac2-b326-2341b55fa568)


===

需要修改的脚本大致有:config.h, [statusbar/packages](https://github.com/yaocccc/dwm/tree/master/DEF/statusbar/packages) 中的脚本，等 

===
此外对于最开始的 aur中找不到 nerd-fonts-jetbrains-mono 字体的问题的解决方法同2楼，直接用pacman在官方源中安装 [ttf-jetbrains-mono-nerd](https://archlinux.org/packages/extra/any/ttf-jetbrains-mono-nerd/) 即可

@EssenSea
