### ISSUE TITLE
麻烦问下大佬

### ISSUE THREAD

**Issue by luobozz** [yaocccc/dwm#5]
[你视频里的状态栏是这个仓库里的实现的吗[](url)](url)
![2023-01-12_18-07](https://user-images.githubusercontent.com/50447466/212038613-56ccfcd0-3aaa-4a6f-8fea-4880430dd821.png)

**Comment by yaocccc** [comment]
是的，而且现在比那时候视频里的多了更多内容和实现，包括点击等等
