### ISSUE TITLE
启动statusbar需要密码

### ISSUE THREAD

**Issue by fecet** [yaocccc/dwm#8]
statusbar中的代码含有sudo, 但在startx启动的时候不会询问密码, 会导致启动失败.

这个问题怎么解决呢

**Comment by yaocccc** [comment]
1. 可以自己手动改掉需要sudo权限的部分。
2. 编辑sudoers文件，添加 %wheel ALL=(ALL:ALL) NOPASSWD: ALL，这个可以sudo命令完全不需要密码
