### ISSUE TITLE
WIFI   状态栏脚本在英语环境下不能正常工作

### ISSUE THREAD

**Issue by starknt** [yaocccc/dwm#9]
声音脚本和 WIFI 脚本似乎有冲突。
- 系统语言为 en_US.UTF-8 下，声音脚本才能正常工作，WIFI 脚本只会显示`无连接`
- 系统语言为 zh_CN.UTF-8 下，WIFI 脚本才能正常工作，声音脚本只会显示`--%`

```bash
localectl
System Locale: LANG=en_US.UTF-8
    VC Keymap: (unset)
    X11 Layout: (unset)
```

**Comment by yaocccc** [comment]
> 声音脚本和 WIFI 脚本似乎有冲突。
> 
> * 系统语言为 en_US.UTF-8 下，声音脚本才能正常工作，WIFI 脚本只会显示`无连接`
> * 系统语言为 zh_CN.UTF-8 下，WIFI 脚本才能正常工作，声音脚本只会显示`--%`
> 
> ```shell
> localectl
> System Locale: LANG=en_US.UTF-8
>     VC Keymap: (unset)
>     X11 Layout: (unset)
> ```

大概知道为啥，因为本身就是根据关键字过滤的，中文和英文环境下关键字不同。

**Comment by yaocccc** [comment]
> 声音脚本和 WIFI 脚本似乎有冲突。
> 
> * 系统语言为 en_US.UTF-8 下，声音脚本才能正常工作，WIFI 脚本只会显示`无连接`
> * 系统语言为 zh_CN.UTF-8 下，WIFI 脚本才能正常工作，声音脚本只会显示`--%`
> 
> ```shell
> localectl
> System Locale: LANG=en_US.UTF-8
>     VC Keymap: (unset)
>     X11 Layout: (unset)
> ```

麻烦在zh_CN下执行一下pactl info看发我看看

**Comment by starknt** [comment]
感谢你的回复， 这个问题似乎可以通过判断当前的语言环境解决，我或许可以开一个PR。

```bash
pactl info
服务器字串：/run/user/1000/pulse/native
程序库协议版本：35
服务器协议版本：35
是否本地服务器：是
客户端索引：4
区块大小: 65472
用户名：avatar
主机名：starkntArch
服务器名：pulseaudio
服务器版本：16.1
默认采样规格：s16le 2ch 44100Hz
默认声道映射：front-left,front-right
默认音频入口：alsa_output.pci-0000_00_1f.3.analog-stereo
默认信源： alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie：024c:15de
```

**Comment by yaocccc** [comment]
我来修复一下吧，我做了比较大的改动

**Comment by yaocccc** [comment]
你再试试看

**Comment by starknt** [comment]
> 你再试试看

目前工作得非常好，是否需要我来关闭 #9
